#!/usr/bin/env python3
"""
generate_config.py
------------------
Reads a YAML configuration file and injects the CONFIG block into one or
more HTML tools inside the ../tools/ directory.

Usage
-----
    # Generate all tools from default config
    python generate_config.py

    # Generate a specific tool
    python generate_config.py --tool roi-calculator

    # Use a custom config file
    python generate_config.py --config my-config.yaml

    # Dry run (print output, don't write files)
    python generate_config.py --dry-run

Requirements
------------
    pip install pyyaml
"""

import argparse
import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml is required. Run: pip install pyyaml")
    sys.exit(1)


# ── Paths ────────────────────────────────────────────────────────────────────

ROOT        = Path(__file__).parent.parent
TOOLS_DIR   = ROOT / "tools"
CONFIG_DIR  = Path(__file__).parent / "configs"
DEFAULT_CFG = CONFIG_DIR / "default.yaml"

# ── Tool registry ─────────────────────────────────────────────────────────────
# Maps tool slug → HTML filename.
TOOLS = {
    "roi-calculator":        "roi-calculator.html",
    "coo-gap-visualizer":    "coo-gap-visualizer.html",
    "revops-roadmap-simulator": "revops-roadmap-simulator.html",
}


# ── Core logic ────────────────────────────────────────────────────────────────

def load_config(config_path: Path) -> dict:
    """Load and validate a YAML config file."""
    if not config_path.exists():
        print(f"ERROR: Config file not found: {config_path}")
        sys.exit(1)
    with open(config_path, "r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)
    if not isinstance(cfg, dict):
        print("ERROR: Config file must be a YAML mapping at the top level.")
        sys.exit(1)
    return cfg


def config_to_js(cfg: dict, tool_key: str) -> str:
    """
    Extract the tool-specific section from the config dict and serialise
    it as a JavaScript const CONFIG = { ... }; block.
    """
    tool_cfg = cfg.get(tool_key, {})
    # Merge with any shared/global keys
    global_cfg = {k: v for k, v in cfg.items() if k not in TOOLS}
    merged = {**global_cfg, **tool_cfg}

    js_obj = json.dumps(merged, indent=2, ensure_ascii=False)
    timestamp = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    return (
        f"/* AUTO-GENERATED by generate_config.py on {timestamp}\n"
        f"   Source: {DEFAULT_CFG.name}\n"
        f"   Do not edit this block manually — edit the YAML config instead. */\n"
        f"const CONFIG = {js_obj};"
    )


def inject_config(html: str, js_block: str) -> str:
    """
    Replace the CONFIG block inside the HTML file.

    The script expects the existing CONFIG to be delimited by:
        /* ===...=== */
        const CONFIG = { ... };
        /* ===...=== */
    """
    pattern = re.compile(
        r"/\* =+\n\s+CONFIG.*?\n\s+=+ \*/"  # opening banner
        r".*?"                               # CONFIG body (non-greedy)
        r"/\* =+ \*/",                       # closing banner
        re.DOTALL,
    )

    replacement = (
        "/* " + "=" * 60 + "\n"
        "   CONFIG — Auto-generated. Edit scripts/configs/default.yaml\n"
        "   " + "=" * 60 + " */\n"
        + js_block + "\n"
        "/* " + "=" * 60 + " */"
    )

    updated, n = pattern.subn(replacement, html)
    if n == 0:
        print("  WARN: CONFIG delimiter not found — file was not modified.")
    return updated


def process_tool(tool_key: str, cfg: dict, dry_run: bool = False) -> bool:
    """Inject config into a single HTML tool. Returns True on success."""
    filename = TOOLS.get(tool_key)
    if not filename:
        print(f"  SKIP: Unknown tool '{tool_key}'")
        return False

    html_path = TOOLS_DIR / filename
    if not html_path.exists():
        print(f"  SKIP: File not found — {html_path}")
        return False

    html = html_path.read_text(encoding="utf-8")
    js_block = config_to_js(cfg, tool_key)
    updated = inject_config(html, js_block)

    if dry_run:
        print(f"\n{'─'*60}")
        print(f"DRY RUN: {filename}")
        print(f"{'─'*60}")
        # Print only the generated CONFIG block for review
        print(js_block[:800] + (" ..." if len(js_block) > 800 else ""))
    else:
        html_path.write_text(updated, encoding="utf-8")
        print(f"  OK: {filename} updated")

    return True


# ── Validation helpers ────────────────────────────────────────────────────────

REQUIRED_KEYS = {
    "roi-calculator":           ["title", "subtitle", "currency", "investment"],
    "coo-gap-visualizer":       ["title", "dimensions", "benchmark"],
    "revops-roadmap-simulator": ["title", "CATEGORIES", "TEMPLATES"],
}


def validate_config(cfg: dict) -> list[str]:
    """Return a list of validation errors (empty = valid)."""
    errors = []
    for tool, keys in REQUIRED_KEYS.items():
        tool_cfg = {**cfg, **cfg.get(tool, {})}
        for key in keys:
            if key not in tool_cfg:
                errors.append(f"[{tool}] missing required key: '{key}'")
    return errors


# ── CLI ───────────────────────────────────────────────────────────────────────

def parse_args():
    parser = argparse.ArgumentParser(
        description="Inject YAML config into b2b-growth-tools HTML files."
    )
    parser.add_argument(
        "--tool",
        choices=list(TOOLS.keys()) + ["all"],
        default="all",
        help="Which tool to update (default: all)",
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=DEFAULT_CFG,
        help=f"Path to YAML config file (default: {DEFAULT_CFG})",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated CONFIG blocks without writing files",
    )
    parser.add_argument(
        "--validate",
        action="store_true",
        help="Validate config structure without generating files",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    cfg  = load_config(args.config)

    print(f"Config loaded: {args.config}")

    # Validate
    errors = validate_config(cfg)
    if errors:
        print("\nConfig validation errors:")
        for e in errors:
            print(f"  ✗ {e}")
        if args.validate or not args.dry_run:
            sys.exit(1)
    else:
        print("Config validation: OK")

    if args.validate:
        print("Validation complete — no files written.")
        return

    # Process
    tools_to_run = list(TOOLS.keys()) if args.tool == "all" else [args.tool]
    print(f"\nProcessing {len(tools_to_run)} tool(s)...")

    success = 0
    for tool_key in tools_to_run:
        print(f"\n→ {tool_key}")
        if process_tool(tool_key, cfg, dry_run=args.dry_run):
            success += 1

    print(f"\nDone: {success}/{len(tools_to_run)} tools {'previewed' if args.dry_run else 'updated'}.")


if __name__ == "__main__":
    main()
